### ISSUE TITLE
Writing to refile.org from panel

### ISSUE THREAD

**Issue by Daemsen** [ihdavids/orgextended_docs#13]
Hi!

First of all thank you so much for all your effort. I really enjoy using your plugin so far!

I am currently facing the following issue, that I cant't solve by my own:

When using  the Capture function, I want to use the panel for taking quick notes. The panel opens and I press ESC as soon as I finished writing the quick notes. How ever, it is not writing the notes to the refile.org file that I created. 

When I change the settings to openas: direct, it opens the file and i can do my notes there. But I would prefer to use the panel.

Any ideas what I am doing wrong? 

Thanks and greetings from Germany.
Damian

**Comment by ihdavids** [comment]
Most likely the panel code is throwing an exception.
Often this isbdue to spaces in a path or saving somewhere it doesnt have permission. If you can grab the console output that could help understand this.

Sadly the panel api is really lacking in sublime so that code is already really brittle. The panel popup has been one of my greater frustrations with the plugin. Honestly i mostly use the direct flavor now because of popup size and placement problems, so issues like this tend to get missed.

If you can capture the ctrl ' console exception i will see about patching it.

**Comment by ihdavids** [comment]
Easier for me in the future if you report bugs on the orgextended repo rather than the docs and report docs issues here. It has a template that prompts for exceptions et al. Docs are separate as i got feedback not to ship the docs with the plugin a while back. :)

**Comment by ihdavids** [comment]
Looks like you already have? I see your post on the previous jimzhuang issue.
Great! I will close this one out and reopen that one for more investigation.
