### ISSUE TITLE
Tab Expand/Collapse Does Not Work Unless File Is Saved To Disk

### ISSUE THREAD

**Issue by Anti-Distinctlyminty** [ihdavids/orgextended_docs#2]
Open a new blank file in Sublime, paste and org document into it, then set the syntax to OrgExtended. Then try to tab expand and collapse some items. No expansion of collapsing takes place.

**Comment by ihdavids** [comment]
I am going to move this to the OrgExtended repo rather than the docs. (Originally these docs were part of the main project but I pulled them out to avoid having package users having to pay the cost for them)

Heh. I save so reflexively that I have honestly never noticed this bug! Thank you for pointing it out. I will work to resolve this as I can make time.

**Comment by ihdavids** [comment]
Moved here:

https://github.com/ihdavids/orgextended/issues/8

A fix for this should be coming in 1.0.8

**Comment by ihdavids** [comment]
1.0.8 is pushed, should be available in an hour
